
import rigidbody2d.Engine;
import rigidbody2d.PointMass;
import rigidbody2d.RigidBody;
import rigidbody2d.vecmath.Vector2D;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrea
 */
public class RigidBodyTest extends javax.swing.JFrame {
    
    PointMass[] pms;
    Engine engine;
    RigidBody body;
    
    /**
     * Creates new form RigidBodyTest
     */
    public RigidBodyTest() {
        initComponents();
        
        engine = new Engine();
        
        pms = new PointMass[4];
        
        pms[0] = new PointMass(10, 10, 1);
        pms[1] = new PointMass(10, 50, 1);
        pms[2] = new PointMass(50, 50, 1);
        pms[3] = new PointMass(50, 10, 1);
        
        body = new RigidBody(new Vector2D(20, 0), (float)(Math.PI / 4), pms);
        //body = new RigidBody(pms);
        
        //body.addForce(UniformForce.GRAVITY);
        
        engine.addRigidBody(body);
        
        pms = new PointMass[4];
        
        pms[0] = new PointMass(210, 10, 1);
        pms[1] = new PointMass(210, 50, 1);
        pms[2] = new PointMass(250, 50, 1);
        pms[3] = new PointMass(250, 10, 1);
        
        body = new RigidBody(new Vector2D(-20, 0), (float)(2*Math.PI), pms);       
        
        engine.addRigidBody(body);
        
        engine.start();
        
        rbPanel.setEngine(engine);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbPanel = new rigidbody2dx.RigidBodyPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rbPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RigidBodyTest.this.mousePressed(evt);
            }
        });

        javax.swing.GroupLayout rbPanelLayout = new javax.swing.GroupLayout(rbPanel);
        rbPanel.setLayout(rbPanelLayout);
        rbPanelLayout.setHorizontalGroup(
            rbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );
        rbPanelLayout.setVerticalGroup(
            rbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rbPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rbPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mousePressed
        
        //Vector2D mouse = new Vector2D(evt.getX(), evt.getY());
        
        //System.out.println(body.contains(evt.getX(), evt.getY()));
        
        /*
        for(PointMass p : pms)
            if(p.getPosition().sub(mouse).length() <= 10)
                body.addForce(new ConstantAppliedForce(p, new Vector2D(10, 0)));*/
        
    }//GEN-LAST:event_mousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RigidBodyTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RigidBodyTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RigidBodyTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RigidBodyTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RigidBodyTest().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rigidbody2dx.RigidBodyPanel rbPanel;
    // End of variables declaration//GEN-END:variables
}
